/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectstia2;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class GuiOwner extends javax.swing.JFrame {

    /**
     * Creates new form GuiOwner
     */
    public GuiOwner() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LaccNum = new javax.swing.JLabel();
        tfaccNum = new javax.swing.JTextField();
        Ldate = new javax.swing.JLabel();
        CbDate = new javax.swing.JComboBox<>();
        Lname = new javax.swing.JLabel();
        tfname = new javax.swing.JTextField();
        Ladd = new javax.swing.JLabel();
        tfadd = new javax.swing.JTextField();
        Larrears = new javax.swing.JLabel();
        tfarrears = new javax.swing.JTextField();
        LpreMeter = new javax.swing.JLabel();
        tfpreMeter = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfcurMeter = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfunit = new javax.swing.JTextField();
        Lcharge = new javax.swing.JLabel();
        tfcharge = new javax.swing.JTextField();
        Lbill = new javax.swing.JLabel();
        tfbill = new javax.swing.JTextField();
        BtnSave = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnDisplay = new javax.swing.JButton();
        BtnEdit = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();
        BtnReset = new javax.swing.JButton();
        BtnExits = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDisplay = new javax.swing.JTextArea();
        btncalculation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setText("ELECTRICITY BILLING SYSTEM");

        LaccNum.setText("Account Number");

        Ldate.setText("Bill Date ");

        CbDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHOOSE YOUR DATE", "JANUARY", "FEBRUARY", "MARCH", "APRIL", "JUNE", "JULY", "AUGUST", "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER" }));

        Lname.setText("Name");

        Ladd.setText("Address");

        Larrears.setText("Arrears");

        LpreMeter.setText("Previous Meter");

        jLabel2.setText("Current Meter");

        jLabel3.setText("Total Unit");

        tfunit.setEditable(false);

        Lcharge.setText("Current Charge");

        Lbill.setText("Total Bill");

        tfbill.setEditable(false);

        BtnSave.setText("Add&Save");
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnDisplay.setText("Display");
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });

        BtnEdit.setText("Edit");
        BtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditActionPerformed(evt);
            }
        });

        BtnDelete.setText("Delete");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        BtnReset.setText("Reset");
        BtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResetActionPerformed(evt);
            }
        });

        BtnExits.setText("Exits");
        BtnExits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitsActionPerformed(evt);
            }
        });

        taDisplay.setColumns(20);
        taDisplay.setRows(5);
        jScrollPane1.setViewportView(taDisplay);

        btncalculation.setText("Calculation");
        btncalculation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalculationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LaccNum)
                            .addComponent(Ldate)
                            .addComponent(Lname)
                            .addComponent(Ladd)
                            .addComponent(Larrears)
                            .addComponent(LpreMeter)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(Lcharge)
                            .addComponent(Lbill))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfaccNum)
                            .addComponent(CbDate, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfname)
                            .addComponent(tfadd)
                            .addComponent(tfarrears)
                            .addComponent(tfpreMeter)
                            .addComponent(tfcurMeter)
                            .addComponent(tfunit)
                            .addComponent(tfcharge)
                            .addComponent(tfbill, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(298, 298, 298)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BtnExits)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BtnSave)
                                        .addGap(32, 32, 32)
                                        .addComponent(btnSearch)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnDisplay)))
                                .addGap(18, 18, 18)
                                .addComponent(BtnEdit)
                                .addGap(18, 18, 18)
                                .addComponent(BtnDelete)
                                .addGap(18, 18, 18)
                                .addComponent(BtnReset)
                                .addGap(18, 18, 18)
                                .addComponent(btncalculation)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LaccNum)
                            .addComponent(tfaccNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Ldate)
                            .addComponent(CbDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lname)
                            .addComponent(tfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ladd)
                            .addComponent(tfadd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Larrears)
                            .addComponent(tfarrears, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfpreMeter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LpreMeter))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfcurMeter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(tfunit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lcharge)
                            .addComponent(tfcharge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lbill)
                            .addComponent(tfbill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSave)
                    .addComponent(btnSearch)
                    .addComponent(btnDisplay)
                    .addComponent(BtnEdit)
                    .addComponent(BtnDelete)
                    .addComponent(BtnReset)
                    .addComponent(btncalculation))
                .addGap(18, 18, 18)
                .addComponent(BtnExits)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
        // TODO add your handling code here:
        Owners own;
        OwnerOperation Operation = new OwnerOperation();
        
        int AccNum = Integer.parseInt(tfaccNum.getText()); // get data in String from textfield staff No and convert into integer
        String billDate = String.valueOf(CbDate.getSelectedItem());
        String name = tfname.getText(); // get data in String from textfield name
        String address = tfadd.getText(); 
        double arrears= Double.parseDouble(tfarrears.getText()); // get data in String from textfield salary and convert into double
        double preMeter= Double.parseDouble(tfpreMeter.getText());
        double curMeter= Double.parseDouble(tfcurMeter.getText());
        double totalunit = curMeter-preMeter;
        double charge= Double.parseDouble(tfcharge.getText());
        double totalBill = totalunit+charge;
        
        
        // store a record into an object
        own = new Owners(AccNum, billDate, name, address, arrears, preMeter, curMeter, totalunit, charge, totalBill);
        try {
            Operation.addRecord(own); // add one record into text file
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
        JOptionPane.showMessageDialog(null, "The record has been saved successfully in the text file");
        
        
    }//GEN-LAST:event_BtnSaveActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        OwnerOperation Operation = new OwnerOperation();
        
        int AccNumber = Integer.parseInt(tfaccNum.getText());
        System.out.println("search Account Number = "+AccNumber);
        
        Owners record = null;
        try
        {    
            record = Operation.findRecord(AccNumber);
        }catch (IOException ex)
        {
            System.out.println(ex.getMessage());
        }
        if (record != null)
        {
            AccNumber = record.getAccNum();
            String billDate=record.getBillDate();
            String name = record.getName();
            String address = record.getAddress();    
            double arrears = record.getArrears();
            double preMeter = record.getPreMeter();
            double curMeter = record.getCurMeter();
            double totalUnit = record.getTotalUnit();
            double curCharge = record.getCurCharge();
            double totalBill = record.getTotalBill();
            
            tfaccNum.setText(String.valueOf(AccNumber));
            tfbill.setText(billDate);
            tfname.setText(name); 
            tfadd.setText(address);
            tfarrears.setText(String.valueOf(arrears));
            tfpreMeter.setText(String.valueOf(preMeter));
            tfcurMeter.setText(String.valueOf(curMeter));
            tfunit.setText(String.valueOf(totalUnit));
            tfcharge.setText(String.valueOf(curCharge));
            tfbill.setText(String.valueOf(totalBill));
            
            
            int month = CbDate.getItemCount(); // get the number of items in combobBox
            for (int i=0; i<month; i++)
            {
                String months = String.valueOf(CbDate.getItemAt(i)).trim(); // get item in combo box (in Object type) and convert into String
                System.out.println(months);
                if (billDate.equals(months))
                {    
                    CbDate.setSelectedIndex(i);
                    //System.out.println());
                }
            }
            
            taDisplay.setText("OWNER RECORD\n");
            taDisplay.append("\nACCOUNT NO \t BILL DATE \tNAME \tADDRESS \tARREARS \tPREVIOUS METER \tCURRENT METER \tTOTAL UNIT \tCURRENT CHARGE \tTOTAL BILL\n");
            taDisplay.append(AccNumber+"\t"+billDate+"\t"+name+"\t"+address+"\t"+arrears+"\t"+preMeter+"\t"+curMeter+"\t"+totalUnit+"\t"+curCharge+"\t"+totalBill+"\n");
            JOptionPane.showMessageDialog(null, "The record of "+AccNumber+" is found successfully");
        }
        else // if record == null
        {
            JOptionPane.showMessageDialog(null, "The record of "+AccNumber+" is not found");
            taDisplay.setText("The record of Account Number = "+AccNumber+" is not found");
        }
            
            
        
    }                                         

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        OwnerOperation Operation = new OwnerOperation();
        ArrayList <Owners> owns = new ArrayList <Owners>();
        Owners own = null;
        
        int AccNumber = Integer.parseInt(tfaccNum.getText());
        System.out.println("search Account Number = "+AccNumber);
        
        try
        {
            owns = Operation.readAllRecordFromFile(); // read all records in text file and store it in arraylist
            for(int i=0; i<owns.size(); i++)
            {
                if (AccNumber == owns.get(i).getAccNum())
                {
                    own = owns.get(i);
                    owns.remove(i);
                    Operation.addAllRecordInFile(owns);
                    JOptionPane.showMessageDialog(null, "The record of \n"+own.getAccNum()+"\n"+own.getName()+"\nhas been deleted successfully");
                    taDisplay.setText("The record of "+own.getAccNum()+"\t"+own.getName()+"has been deleted successfully");
                }
            }
            if (own == null)
                JOptionPane.showMessageDialog(null, "The record of "+AccNumber+" is not found");
        }
        catch(IOException ex)
        {
            System.out.println(ex.getMessage());
        }
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
        // TODO add your handling code here:
        
        ArrayList <Owners> emps;
        OwnerOperation Operation = new OwnerOperation();
        
        taDisplay.setText("OWNER LIST\n");
        taDisplay.append("\nACCOUNT NUMBER \tBILL DATE \tNAME \tADDRESS \t\tARREARS\tPREVIOUS METER \tCURRENT METER \tTOTAL UNIT \tCURRENT CHARGE \t TOTAL BILL\n");
        
        
        try 
        {
            
            emps = Operation.displayAllRecord(); //  emps = employees
            for (int i=0; i<emps.size(); i++)
            {
                String accNum = String.valueOf(emps.get(i).getAccNum());
                String billDate = String.valueOf(emps.get(i).getBillDate());
                String name = emps.get(i).getName();
                String address = emps.get(i).getAddress();
                String arrears = String.valueOf(emps.get(i).getArrears());
                String preMeter = String.valueOf(emps.get(i).getPreMeter());
                String curMeter = String.valueOf(emps.get(i).getCurMeter());
                String totalUnit = String.valueOf(emps.get(i).getTotalUnit());
                String charge = String.valueOf(emps.get(i).getCurCharge());
                String totalBill = String.valueOf(emps.get(i).getTotalBill()); 
                taDisplay.append(accNum+"\t"+billDate+"\t"+name+"\t"+address+"\t\t"+arrears+"\t"+preMeter+"\t"+curMeter+"\t"+totalUnit+"\t"+charge+"\t"+totalBill+"\n");
                //System.out.printf("%-6d %-25s %-10s %-25s %-10s %8.2f %8.2f  %8.2f  %8.2f \n",emps.get(i).getAccNum(),name,gender,address, state, emps.get(i).getSalary(), emps.get(i).getAllowance(), emps.get(i).getDeduction(), emps.get(i).getNetSalary());
                
                
                
            }
        } catch (IOException ex) 
        {
            System.out.println(ex.getMessage());
        }
        
         
        
    }//GEN-LAST:event_btnDisplayActionPerformed

    private void BtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEditActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        // TODO add your handling code here:
        OwnerOperation Operation = new OwnerOperation();
        ArrayList <Owners> owns = new ArrayList <Owners>();
        Owners own = null;
        
        int AccNumber = Integer.parseInt(tfaccNum.getText());
        System.out.println("search Account Number = "+AccNumber);
        
        try
        {
            owns = Operation.readAllRecordFromFile(); // read all records in text file and store it in arraylist
            for(int i=0; i<owns.size(); i++)
            {
                if (AccNumber == owns.get(i).getAccNum())
                {
                    own = owns.get(i);
                    owns.remove(i);
                    Operation.addAllRecordInFile(owns);
                    JOptionPane.showMessageDialog(null, "The record of \n"+own.getAccNum()+"\n"+own.getName()+"\nhas been deleted successfully");
                    taDisplay.setText("The record of "+own.getAccNum()+"\t"+own.getName()+"has been deleted successfully");
                }
            }
            if (own == null)
                JOptionPane.showMessageDialog(null, "The record of "+AccNumber+" is not found");
        }
        catch(IOException ex)
        {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void BtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResetActionPerformed
        // TODO add your handling code here:
        tfaccNum.setText("");
        tfname.setText("");
         // make the two radio buttons to be unselected
        tfadd.setText("");
        CbDate.setSelectedIndex(0); // make a combobox set to the first item
        tfarrears.setText("");
        tfpreMeter.setText("");
        tfcurMeter.setText("");
        tfunit.setText("");
        tfbill.setText("");
        taDisplay.setText("");
        
        
    }//GEN-LAST:event_BtnResetActionPerformed

    private void BtnExitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnExitsActionPerformed

    private void btncalculationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalculationActionPerformed
        // TODO add your handling code here:
        Owners owner;
        OwnerOperation Operation = new OwnerOperation();
        
        double preMeter= Double.parseDouble(tfpreMeter.getText());
        double curMeter= Double.parseDouble(tfcurMeter.getText());
        
        double totalunit=preMeter-curMeter;
        tfunit.setText(String.valueOf(totalunit));
        
        double charge=Operation.calculateCurrentCharge(totalunit);
        tfcharge.setText(charge+"");
        
        double arrears=Double.parseDouble(tfarrears.getText());
        double totalBill=arrears-charge;
        tfbill.setText(String.valueOf(totalBill));
       
        
    }//GEN-LAST:event_btncalculationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(GuiOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(GuiOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(GuiOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(GuiOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiOwner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnEdit;
    private javax.swing.JButton BtnExits;
    private javax.swing.JButton BtnReset;
    private javax.swing.JButton BtnSave;
    private javax.swing.JComboBox<String> CbDate;
    private javax.swing.JLabel LaccNum;
    private javax.swing.JLabel Ladd;
    private javax.swing.JLabel Larrears;
    private javax.swing.JLabel Lbill;
    private javax.swing.JLabel Lcharge;
    private javax.swing.JLabel Ldate;
    private javax.swing.JLabel Lname;
    private javax.swing.JLabel LpreMeter;
    private javax.swing.JButton btnDisplay;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btncalculation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taDisplay;
    private javax.swing.JTextField tfaccNum;
    private javax.swing.JTextField tfadd;
    private javax.swing.JTextField tfarrears;
    private javax.swing.JTextField tfbill;
    private javax.swing.JTextField tfcharge;
    private javax.swing.JTextField tfcurMeter;
    private javax.swing.JTextField tfname;
    private javax.swing.JTextField tfpreMeter;
    private javax.swing.JTextField tfunit;
    // End of variables declaration//GEN-END:variables
}
